// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Product 1 description...",
                            Name = "Product 1",
                            Price = 538.0,
                            Stock = 93
                        },
                        new
                        {
                            Id = 2,
                            Description = "Product 2 description...",
                            Name = "Product 2",
                            Price = 871.0,
                            Stock = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Product 3 description...",
                            Name = "Product 3",
                            Price = 834.0,
                            Stock = 39
                        },
                        new
                        {
                            Id = 4,
                            Description = "Product 4 description...",
                            Name = "Product 4",
                            Price = 869.0,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            Description = "Product 5 description...",
                            Name = "Product 5",
                            Price = 290.0,
                            Stock = 14
                        },
                        new
                        {
                            Id = 6,
                            Description = "Product 6 description...",
                            Name = "Product 6",
                            Price = 957.0,
                            Stock = 12
                        },
                        new
                        {
                            Id = 7,
                            Description = "Product 7 description...",
                            Name = "Product 7",
                            Price = 470.0,
                            Stock = 39
                        },
                        new
                        {
                            Id = 8,
                            Description = "Product 8 description...",
                            Name = "Product 8",
                            Price = 262.0,
                            Stock = 99
                        },
                        new
                        {
                            Id = 9,
                            Description = "Product 9 description...",
                            Name = "Product 9",
                            Price = 740.0,
                            Stock = 84
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
